image: clockwise/docker-phpunit-alpain:master
pipelines:
  default:
    - step:
        deployment: test
        name: Build and test
        caches:
          - composer
        script:
          - composer --version
          - composer install
          - vendor/bin/phpunit --version
          - cp .env.example .env
          - touch database/database.sqlite
          - php artisan migrate --seed
          - vendor/bin/phpunit