image: clockwise/docker-phpunit-alpain:master
pipelines:
  default:
    - step:
        name: Build
        caches:
          - composer
        script:
          - composer --version
          - composer install
          - vendor/bin/phpunit --version
          - cp .env.example .env
          - touch database/database.sqlite
          - php artisan migrate --seed
    - step:
        name: test phpunit
        script:
          # run tests
          - vendor/bin/phpunit