version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Worker
  worker:
    build:
      context: ./
      dockerfile: ./docker/worker.dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/supervisor/:/var/log/supervisor/

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    restart: always
    working_dir: /var/www
    volumes_from:
      - app
    volumes:
      - ./docker/nginx/:/var/log/nginx
    ports:
      - ${APP_PORT}:80

  # The Database
  database:
    restart: always
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
        - "33061:3306"

  redis:
    restart: always
    image: redis:latest
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]

volumes:
  dbdata: